name: Build magiskboot

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: topjohnwu/Magisk
        ref: master
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: sudo apt-get update && sudo apt-get install -y ninja-build
    - uses: nttld/setup-ndk@v1
      id: ndk
      with:
        ndk-version: r26d
    - run: |
        export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
        python build.py native
    - uses: actions/upload-artifact@v4
      with:
        name: magiskboot-linux-armeabi-v7a
        path: out/native/armeabi-v7a/magiskboot
    - uses: actions/upload-artifact@v4
      with:
        name: magiskboot-linux-arm64-v8a
        path: out/native/arm64-v8a/magiskboot
    - uses: actions/upload-artifact@v4
      with:
        name: magiskboot-linux-x86
        path: out/native/x86/magiskboot
    - uses: actions/upload-artifact@v4
      with:
        name: magiskboot-linux-x86_64
        path: out/native/x86_64/magiskboot
