name: Build magiskboot

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: topjohnwu/Magisk
        ref: master
        submodules: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: sudo apt-get update && sudo apt-get install -y ninja-build
    - run: python build.py ndk
    - run: python build.py native
    - uses: actions/upload-artifact@v4
      with:
        name: magiskboot-all
        path: out/native/*/magiskboot
